# Generated by Django 5.0.4 on 2024-07-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_factura', models.CharField(max_length=255)),
                ('nit_factura', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('monto', models.FloatField(default=0)),
                ('precio_actual_producto', models.FloatField()),
                ('cantidad_producto', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.bomba')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.combustible')),
            ],
        ),
    ]
