# Generated by Django 5.0.4 on 2024-07-11 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='surtidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.surtidor'),
        ),
    ]
