# Generated by Django 5.0.4 on 2024-07-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_surtidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
