# Generated by Django 5.0.4 on 2024-07-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustible',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
