# Generated by Django 5.0.4 on 2024-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0004_insert_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surtidor',
            name='latitud',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='surtidor',
            name='longitud',
            field=models.CharField(max_length=255),
        ),
    ]
