# Generated by Django 5.0.4 on 2024-07-12 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('camion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='refineria.camion')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('litros_combustible', models.FloatField()),
                ('tipo_combustible', models.CharField(max_length=50)),
                ('precio_por_litro', models.FloatField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refineria.camion')),
            ],
        ),
        migrations.CreateModel(
            name='SurtidorRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surtidor_id', models.IntegerField()),
                ('litros_entrega', models.FloatField()),
                ('completado', models.BooleanField(default=False)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surtidores', to='refineria.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='camion',
            name='tipo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refineria.tipocombustible'),
        ),
    ]
