# Generated by Django 5.0.4 on 2024-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refineria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Chofer',
        ),
    ]
