# Generated by Django 5.0.4 on 2024-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refineria', '0002_camion_user_id_delete_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
