# Generated by Django 5.0.4 on 2024-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refineria', '0003_ruta_completado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surtidor_id', models.IntegerField()),
                ('tipo_combustible', models.IntegerField()),
                ('isDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='surtidorruta',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
