# Generated by Django 5.0.4 on 2024-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refineria', '0004_solicitud_surtidorruta_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='litros_solicitados',
            field=models.IntegerField(default=0),
        ),
    ]
